<?php
/* Datei: fields_products_page.inc
 * Zweck: Definiert die Variablen und erstellt die
 * zur Anzeige der Produktseite des Katalogs 
 * erforderlichen Arrays
 */
$page = array( "title" => "Der Baumarkt",
	       "top"   => "Der Baumarkt",
	       "bottom" => "Bei Fragen und Anregungen wenden Sie sich an admin@heimwerker.de",
	     );
$table_heads = array("katalog_nr" => "Kat.Nr.",
		     "name"	  => "Bezeichnung",
		     "fabrikat"   => "Fabrikat",
		     "best_nr"    => "Bestellnr",
		     "preis"      => "Preis",
		    );
?>
